GET http://localhost:3009/api/blog


###
DELETE  http://localhost:3009/api/blog/614c471bc8abc353a174054a

###
POST http://localhost:3009/api/blog 
content-type: application/json
                                                                  
{
    "title":"ogede",
    "author":"lajaCodes",
    "url": "laja/002",
    "likes": 9
}

###
PUT http://localhost:3009/api/blog/614c4522ff1a6f61d66b19e6
content-type: application/json
                                                          
{
    "title":"is okay",
    "author":"lajaOlowo",
    "url": "laj/000",
    "likes": 2
}
