GET http://localhost:3009/api/blog


###
DELETE  http://localhost:3009/api/blog/614c471bc8abc353a174054a

###
POST http://localhost:3009/api/blog 
content-type: application/json
                                                                  
{
    "title":"ogede",
    "author":"lajaCodes",
    "url": "laja/002",
    "likes": 987656782990
}

###
PUT http://localhost:3009/api/blog/613602c85a846c79d8dce875
content-type: application/json
                                                          
{
    "title":"academics",
    "author":"lajaMoney",
    "url": "laja/000",
    "likes": 6
}
